# Generated by Django 4.2.6 on 2023-10-28 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("no_of_guests", models.IntegerField(blank=True, null=True)),
                ("bookingdate", models.DateTimeField(auto_now_add=True, null=True)),
                ("reservation_slot", models.SmallIntegerField(default=10)),
                (
                    "reservation_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            10,
                            28,
                            18,
                            42,
                            49,
                            778505,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("inventory", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
