# Generated by Django 4.2.6 on 2023-10-31 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BookingTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("no_of_guests", models.IntegerField(blank=True, null=True)),
                ("bookingdate", models.DateTimeField(auto_now_add=True, null=True)),
                ("reservation_slot", models.SmallIntegerField(default=10)),
                (
                    "reservation_date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            10,
                            31,
                            14,
                            1,
                            51,
                            824153,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("inventory", models.IntegerField(blank=True, null=True)),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", max_length=1000, null=True
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="restaurant.category",
                    ),
                ),
            ],
        ),
    ]
