# Generated by Django 4.2.6 on 2023-10-29 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingtable",
            name="reservation_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 29, 8, 26, 33, 434020, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
