# Generated by Django 4.2.6 on 2023-10-29 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_bookingtable_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 29, 19, 1, 53, 994674, tzinfo=datetime.timezone.utc)),
        ),
    ]
