# Generated by Django 4.2.6 on 2023-10-30 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_bookingtable_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtable',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 5, 26, 21, 349741, tzinfo=datetime.timezone.utc)),
        ),
    ]
