# Generated by Django 4.2.6 on 2023-10-30 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_bookingtable_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='reservation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 30, 6, 5, 4, 258736, tzinfo=datetime.timezone.utc)),
        ),
    ]
